worker_processes 1;
# daemon off;

error_log stderr;
events {
	worker_connections 1024;
}

pid /tmp/nginx.pid;

http {
	charset utf-8;
	log_format appLog 'NginxLog "$request" $status $body_bytes_sent';
	access_log /dev/stdout appLog;
	default_type application/octet-stream;
	include mime.types;

	sendfile off;
	tcp_nopush on;

	server_tokens off;

	keepalive_timeout 30;
	# Ensure that redirects don't include the internal container PORT - 8080
	port_in_redirect off;

	root /usr/share/nginx/html;

	server {
		listen 8080;
		# index index.html index.htm Default.htm;
		gzip on;
		gzip_types text/plain
			application/json
			application/javascript
			text/css
			image/svg+xml;
		gzip_proxied any;

		location ~* \.(jpg|jpeg|gif|png|css|js|ico|woff|woff2|ttf|svg|wasm)$ {
			expires 600;
			add_header Cache-Control "public, immutable"; # immutable for assets that won't change
		}

		location / {
			# kill cache
			add_header Last-Modified $date_gmt;
			add_header Cache-Control 'no-store, no-cache';
			add_header 'Access-Control-Allow-Origin' '*' always;
			add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;

			if_modified_since off;
			expires off;
			etag off;

			try_files $uri $uri/ /index.html;
		}
	}
}
